### ISSUE TITLE
The albums are empty

### ISSUE THREAD

**Issue by lusum** [paulijar/music#6]
Tested with nextcloud, after this bug [#24](https://github.com/ampache/ampache-xbmc-plugin/issues/24)

The command
http://x.x.x.x/nextcloud/index.php/apps/music/ampache/server/xml.server.php?action=album_songs&auth=xxx8&limit=5000&filter=1

gives
<root>
<total_count>0</total_count>
</root>

And not returns anything.

Nextcloud 22.2.3
Nextcloud music 1.5

edit: Wait, the command is wrong..

**Comment by lusum** [comment]
No, the  command is ok, filter is the number of the album

**Comment by paulijar** [comment]
Thanks for the report. The `action=album_songs` seems to have got broken on Music v1.4.1, more than two months ago. Funny that no-one has reported this before.

**Comment by paulijar** [comment]
Fixed. The official github repo for the Music app is owncloud/music and I created an issue there too, it's linked above. This paulijar/music is just my personal sandbox. That linked issue shall be kept open until the fix gets included to a public release.

**Comment by lusum** [comment]
> Fixed. The official github repo for the Music app is owncloud/music and I created an issue there too, it's linked above. This paulijar/music is just my personal sandbox. That linked issue shall be kept open until the fix gets included to a public release.

Ok, if i will have some issue to create, i  will user owncloud/music.
