### ISSUE TITLE
Cover Picture

### ISSUE THREAD

**Issue by Soko1201** [paulijar/music#8]
Hello !!!

When I share a song and the link is clicked, the cover image no longer shows.
Otherwise the picture was always there. Will it work again?

Thanks

My NextColud 26.0.1 Version

![700-1024](https://user-images.githubusercontent.com/110041577/233603522-c7b6598d-0851-43b0-af7e-a61c8ae7c23a.jpg)

**Comment by paulijar** [comment]
On Nextcloud, the player shown on the link-shared audio files is built-in feature of the cloud, i.e. not provided by the Music app. Apparently, Nextcloud has removed the cover art from that view in some recent version, it is missing at least on NC25 and NC26. I don't know if that has happened on purpose or by accident. Anyway, the situation is the same regardless of if the Music app is enabled or not. Hence, I'll close this issue as out-of-scope for the Music app.
